import {createStore, emptyProject, clone, optionsOf, projectPayload, maxTick, pixelKey, DEFAULT_OPTIONS} from './state.js';
import {History} from './history.js';
import * as api from './api.js';
import {Stage2D} from './stage2d.js';
import {PianoRoll} from './pianoroll.js';
import {Stage3D, canvasGeometry} from './stage3d.js';
import {AudioEngine} from './audio.js';
import {DebugPanel} from './debug_panel.js';

const $ = id => document.getElementById(id);
const store=createStore();
const history=new History(store); const audio=new AudioEngine();
let currentView='stage2d', preview=null, playing=false, tick=0, speed=1, raf=0, lastFrame=0, lastInspector=null, renderedRotation=0;
const els={status:$('debugStatus'),meta:$('debugMeta'),logs:$('debugLogs'),commands:$('debugCommands'),stop:$('stopDebugSide')};
const debug=new DebugPanel(els);

function toast(message){const el=$('toast');el.textContent=message;el.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.classList.remove('show'),2200);}
function setCompileState(text,kind=''){const el=$('compileState');el.textContent=text;el.className='state-pill '+kind;}
function hasSources(){const s=store.get();return Boolean(s.midiBase64&&s.imageBase64);}
function canvasAnchor(s){const o=optionsOf(s);return canvasGeometry(o,Number(o.resolution||128),Number(o.resolution||128)).anchor;}
function renderInfo(){const s=store.get(),p=s.project||{},o=optionsOf(s);$('projectInfo').textContent=`工程：${p.name||'show'}\nMIDI：${s.midiBase64?'已导入':'未导入'}\n图片：${s.imageBase64?'已导入':'未导入'}\n事件：${(s.events||[]).length}\n像素修改：${Object.keys(s.overrides||{}).length}`;const metrics={分辨率:`${o.resolution}×${o.resolution}`,画布:o.surface,缩放:`${o.pixelScale}×`,模式:o.visualMode,旋转:`${Number(o.imageRotation||0)}°`,音符:(s.events||[]).length,物理像素:s.manifest?.estimatedBlockCount||'—'};$('metrics').innerHTML=Object.entries(metrics).map(([k,v])=>`<div class="metric"><span>${k}</span><strong>${v}</strong></div>`).join('');const off=(o.canvasOffset||[0,0,0]).join(', '),origin=(o.origin||[0,64,0]).map(Number);$('canvasPositionInfo').textContent=`画布偏移：(${off})\n预计画布原点：${canvasAnchor(s).join(', ')}\n参考 Minecraft 原点：${origin.join(', ')}\n执行：/piano build ${origin.join(' ')}\n放置器：右键方块顶面，点击方块上方一格作为原点\n偏移值范围：-128 至 128`;$('rotationLabel').textContent=`${Number(o.imageRotation||0)}°`;$('saveProject').disabled=!s.project;$('compilePreview').disabled=!hasSources();$('exportShow').disabled=!hasSources();$('launchDebug').disabled=!hasSources();$('pixelHint').style.display=s.imageBase64?'none':'block';$('rollHint').style.display=s.events?.length?'none':'block';}
function renderPalette(){const s=store.get();const select=$('paletteSelect');select.innerHTML=(s.palette||[]).map((p,i)=>`<option value="${i}">${i}: ${p.name||p.block}</option>`).join('');select.value=String(stage2d.paletteIndex||0);$('paletteSwatches').innerHTML=(s.palette||[]).map((p,i)=>`<span class="swatch ${i===stage2d.paletteIndex?'selected':''}" title="${p.block}" data-index="${i}" style="background:rgb(${p.color.join(',')})"></span>`).join('');$('paletteSwatches').querySelectorAll('.swatch').forEach(el=>el.onclick=()=>{stage2d.setPalette(el.dataset.index);renderPalette();});}
function renderOptions(){
  const o=optionsOf(store.get());
  const specs=[['resolution','分辨率','number'],['pixelScale','像素缩放','number'],['surface','画布面','select'],['visualMode','视觉模式','select'],['timingMode','时间模式','select'],['motionMode','Motion 模式','select'],['motionGravity','重力','number'],['motionDrag','阻力','number'],['motionArcHeight','弧高（无上限）','number'],['canvasGap','画布间距','number'],['canvasOffsetX','偏移 X','number'],['canvasOffsetY','偏移 Y','number'],['canvasOffsetZ','偏移 Z','number'],['canvasLift','画布高度','number'],['baseSpawnPerTick','生成预算','number'],['targetLeadTicks','目标提前','number'],['maxActiveDisplays','活动上限','number']];
  $('optionsForm').innerHTML=specs.map(([key,label,type])=>{let control=type==='select'?(key==='surface'?`<select data-option="${key}"><option>wall_north</option><option>wall_south</option><option>wall_east</option><option>wall_west</option><option>floor</option></select>`:key==='visualMode'?`<select data-option="${key}"><option>display</option><option>physical</option></select>`:key==='motionMode'?`<select data-option="${key}"><option value="arc">arc</option><option value="ballistic">ballistic</option><option value="vanilla">原版物理 (vanilla)</option></select>`:`<select data-option="${key}"><option>adaptive</option><option>fixed</option></select>`):`<input data-option="${key}" type="number" min="${key==='motionArcHeight'||key==='motionGravity'||key==='motionDrag'?'0':'-128'}"${key==='motionGravity'||key==='motionDrag'?' max="1"':''} step="${key==='motionGravity'||key==='motionDrag'?'0.01':key==='motionArcHeight'?'0.1':'1'}">`;return `<label>${label}${control}</label>`;}).join('');
  $('optionsForm').querySelectorAll('[data-option]').forEach(el=>{
    const key=el.dataset.option,offsetIndex={canvasOffsetX:0,canvasOffsetY:1,canvasOffsetZ:2}[key];
    el.value=offsetIndex===undefined?o[key]:Number(o.canvasOffset?.[offsetIndex]||0);
    let before=null;
    const capture=()=>{if(!before)before=history.snapshot();};
    const apply=()=>{
      const current=optionsOf(store.get()),value=el.type==='number'?Number(el.value):el.value;
      if(offsetIndex!==undefined){const offset=[...(current.canvasOffset||[0,0,0])];offset[offsetIndex]=Math.max(-128,Math.min(128,Number.isFinite(value)?value:0));store.get().project.compileOptions.canvasOffset=offset;}
      else {
        store.get().project.compileOptions[key]=value;
        if (key === 'motionMode' && value === 'vanilla') {
          store.get().project.compileOptions.visualMode = 'physical';
          const visual = $('optionsForm').querySelector('[data-option="visualMode"]');
          if (visual) visual.value = 'physical';
        } else if (key === 'visualMode' && value === 'display'
          && store.get().project.compileOptions.motionMode === 'vanilla') {
          store.get().project.compileOptions.motionMode = 'arc';
          const motion = $('optionsForm').querySelector('[data-option="motionMode"]');
          if (motion) motion.value = 'arc';
        }
      }
      store.markDirty();renderInfo();stage2d.draw();stage3d.draw();
    };
    el.onfocus=()=>capture();
    // Update the canvas position while the user is typing, rather than waiting
    // for blur.  ``change`` still commits one undo command for the edit.
    el.oninput=()=>{capture();apply();history.record('修改编排参数',before);before=null;setCompileState('有未编译修改');};
    el.onchange=()=>{if(before){apply();history.record('修改编排参数',before);before=null;}else apply();setCompileState('有未编译修改');};
  });
}
function renderInspector(info=lastInspector){lastInspector=info;if(!info){$('inspector').textContent='选择一个像素或音符';return;}if(info.type==='pixel'){$('inspector').innerHTML=`<div>像素坐标：(${info.x}, ${info.y})</div><div>palette index：${info.paletteIndex??'透明'}</div>`;return;}if(info.type==='selection'){$('inspector').textContent=`已选择 ${info.count} 个像素`;return;}const e=info.event;if(!e){$('inspector').textContent='选择一个音符';return;}$('inspector').innerHTML=`<label>tick <input data-field="tick" type="number" value="${e.tick}"></label><label>note <input data-field="note" type="number" min="0" max="127" value="${e.note}"></label><label>velocity <input data-field="velocity" type="number" min="1" max="127" value="${e.velocity}"></label><label>duration <input data-field="durationTicks" type="number" min="1" value="${e.durationTicks}"></label><label>track <input data-field="track" type="number" value="${e.track||0}"></label><label>channel <input data-field="channel" type="number" value="${e.channel||0}"></label>`;$('inspector').querySelectorAll('[data-field]').forEach(el=>el.onchange=()=>{const v=Number(el.value);roll.updateSelected({[el.dataset.field]:v});renderInfo();});}

const stage2d=new Stage2D($('pixelCanvas'),store,history,renderInspector);
const roll=new PianoRoll($('rollCanvas'),store,history,renderInspector);
const stage3d=new Stage3D($('stage3dCanvas'),store);
stage2d.onChange=()=>{renderInfo();setCompileState('有未编译修改');};roll.onChange=()=>{renderInfo();setCompileState('有未编译修改');};history.onChange=()=>{store.get().history=history.export();$('undo').disabled=!history.canUndo();$('redo').disabled=!history.canRedo();const rotation=Number(optionsOf(store.get()).imageRotation||0);if(rotation!==renderedRotation&&store.get().imageBase64)quantizeImage(store.get().imageBase64);renderInfo();if(store.isDirty())setCompileState('有未编译修改');};

async function preparePalette(){try{const data=await api.palettes();store.get().palette=data.palettes;renderPalette();}catch(e){toast(e.message);}}
function decodeBase64(base64){const bin=atob(base64||'');const bytes=new Uint8Array(bin.length);for(let i=0;i<bin.length;i++)bytes[i]=bin.charCodeAt(i);return bytes;}
function encodeBase64(buffer){const bytes=new Uint8Array(buffer);let binary='';const chunk=0x8000;for(let i=0;i<bytes.length;i+=chunk)binary+=String.fromCharCode(...bytes.subarray(i,i+chunk));return btoa(binary);}
async function quantizeImage(base64){if(!base64||!store.get().palette?.length)return;const blob=new Blob([decodeBase64(base64)]);const url=URL.createObjectURL(blob);try{const img=await new Promise((resolve,reject)=>{const i=new Image();i.onload=()=>resolve(i);i.onerror=reject;i.src=url;});const n=optionsOf(store.get()).resolution||128;const rotation=((Number(optionsOf(store.get()).imageRotation)||0)%360+360)%360;const src=document.createElement('canvas');src.width=img.naturalWidth||img.width;src.height=img.naturalHeight||img.height;src.getContext('2d').drawImage(img,0,0);const rotated=document.createElement('canvas');const swap=rotation===90||rotation===270;rotated.width=swap?src.height:src.width;rotated.height=swap?src.width:src.height;const rctx=rotated.getContext('2d');if(rotation===90){rctx.translate(rotated.width,0);rctx.rotate(Math.PI/2);}else if(rotation===180){rctx.translate(rotated.width,rotated.height);rctx.rotate(Math.PI);}else if(rotation===270){rctx.translate(0,rotated.height);rctx.rotate(-Math.PI/2);}rctx.drawImage(src,0,0);const c=document.createElement('canvas');c.width=n;c.height=n;const ctx=c.getContext('2d');ctx.drawImage(rotated,0,0,n,n);const data=ctx.getImageData(0,0,n,n).data,pal=store.get().palette,pixels=[];for(let y=0;y<n;y++)for(let x=0;x<n;x++){const i=(y*n+x)*4;if(data[i+3]<8)continue;let best=0,dist=Infinity;for(let p=0;p<pal.length;p++){const d=(data[i]-pal[p].color[0])**2+(data[i+1]-pal[p].color[1])**2+(data[i+2]-pal[p].color[2])**2;if(d<dist){dist=d;best=p;}}pixels.push([x,y,best,pixels.length]);}store.get().quantizedPixels=pixels;store.get().manifest={logicalWidth:n,logicalHeight:n};renderedRotation=rotation;stage2d.draw();}finally{URL.revokeObjectURL(url);}}
function rotateCoord(x,y,delta,width,height){if(delta===90)return [height-1-y,x];if(delta===270)return [y,width-1-x];if(delta===180)return [width-1-x,height-1-y];return [x,y];}
function remapRotatedState(delta){const s=store.get(),n=Number(optionsOf(s).resolution||128),map={};for(const [key,value] of Object.entries(s.overrides||{})){const [x,y]=key.split(',').map(Number),next=rotateCoord(x,y,delta,n,n);map[`${next[0]},${next[1]}`]=value;}s.overrides=map;s.selectedPixels=(s.selectedPixels||[]).map(key=>{const [x,y]=key.split(',').map(Number),next=rotateCoord(x,y,delta,n,n);return `${next[0]},${next[1]}`;});if(stage2d.clipboard)stage2d.clipboard=stage2d.clipboard.map(item=>{const next=rotateCoord(item.x,item.y,delta,n,n);return {...item,x:next[0],y:next[1]};});}
async function rotateImage(delta){const s=store.get();if(!s.imageBase64){toast('请先导入图片');return;}const before=history.snapshot(),options=s.project.compileOptions||{};const current=((Number(options.imageRotation)||0)+delta+360)%360;options.imageRotation=current;remapRotatedState((delta+360)%360);await quantizeImage(s.imageBase64);history.record('图像旋转',before);setCompileState('有未编译修改');renderInfo();}
async function importMidi(file){const bytes=await file.arrayBuffer();const b64=encodeBase64(bytes);store.get().midiBase64=b64;store.get().eventsOverride=true;try{const result=await api.analyzeMidi(b64);store.get().events=result.events||[];toast(`已导入 ${result.eventCount||0} 个音符`);}catch(e){store.get().events=[];toast(e.message);}store.markDirty();setCompileState('有未编译修改');renderInfo();roll.draw();}
async function importImage(file){const bytes=await file.arrayBuffer();const b64=encodeBase64(bytes);store.get().imageBase64=b64;store.get().overrides={};await quantizeImage(b64);store.markDirty();setCompileState('有未编译修改');renderInfo();}
function loadState(next){const project={...(next.project||{}),compileOptions:{...DEFAULT_OPTIONS,...(next.project?.compileOptions||{})}};const hasEventOverride=Array.isArray(next.events);store.set({...next,project,events:hasEventOverride?next.events:[],eventsOverride:hasEventOverride,palette:store.get().palette||[],quantizedPixels:next.quantizedPixels||[],selectedPixels:[]},false);history.import(next.history||[]);renderInfo();renderOptions();renderPalette();stage2d.resetView();tick=0;setCompileState('已加载','good');if(next.imageBase64)quantizeImage(next.imageBase64);}
async function openProject(){const f=$('projectFile').files[0];if(!f)return;try{loadState(await api.openProject(f));toast('工程已打开');}catch(e){setCompileState(e.message,'bad');}}
function newProject(){let name='新工程';try{const asked=window.prompt?.('工程名称','新工程');if(asked===null)return;if(asked)name=asked;}catch(_){/* embedded browsers may disable prompt dialogs */}loadState(emptyProject(name));setCompileState('新工程，请导入素材');}
async function save(){try{const r=await api.saveProject(projectPayload(store.get()));const blob=await r.blob();const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`${store.get().project.name||'show'}.pwork`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500);store.markSaved();setCompileState('已保存','good');toast('工程已保存');}catch(e){setCompileState(e.message,'bad');}}
async function compile(){if(!hasSources())return;setCompileState('编译中…');try{const data=await api.compilePreview(projectPayload(store.get()));preview=data;const s=store.get();s.manifest=data.manifest;s.layout=data.layout;s.quantizedPixels=data.pixels;s.palette=data.palette;s.previewPngBase64=data.previewPngBase64;stage3d.setPreview(data);renderPalette();renderInfo();setCompileState('预览已编译','good');toast('编译预览完成');}catch(e){setCompileState(e.message,'bad');}}
async function exportShow(){if(!hasSources())return;try{const r=await api.compileDownload(projectPayload(store.get()));const blob=await r.blob();const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`${store.get().project.name||'show'}.pshow`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500);setCompileState('已导出 v2','good');}catch(e){setCompileState(e.message,'bad');}}
async function launch(){try{const s=await api.launchDebug(projectPayload(store.get()));debug.start(s);setCompileState(s.status==='failed'?(s.error||'启动失败'):'调试运行中',s.status==='failed'?'bad':'good');}catch(e){setCompileState(e.message,'bad');}}
function switchView(view){currentView=view;document.querySelectorAll('.view-tabs button').forEach(b=>b.classList.toggle('active',b.dataset.view===view));document.querySelectorAll('.view-pane').forEach(p=>p.classList.toggle('active',p.id===`${view}View`));$('viewTitle').textContent=view==='stage2d'?'2D 像素画':view==='roll'?'Piano Roll':'3D 舞台';if(view==='stage2d')stage2d.resize();if(view==='roll')roll.resize();if(view==='stage3d')stage3d.resize();}
function transportFrame(now){const dt=Math.min(100,now-lastFrame||0);lastFrame=now;if(playing){tick+=dt/50*speed;if(tick>=maxTick(store.get())){tick=maxTick(store.get());playing=false;}const start=tick-(dt/50*speed);for(const e of store.get().events||[])if(e.tick>=start&&e.tick<=tick)audio.note(e,0,speed);}roll.setPlayhead(tick);stage3d.setPlayhead(tick);$('tickLabel').textContent=`tick ${Math.floor(tick)}`;$('timeline').max=maxTick(store.get());$('timeline').value=Math.min(tick,maxTick(store.get()));raf=requestAnimationFrame(transportFrame);}
function togglePlay(){playing=true;audio.ensure();audio.play(store.get().events||[],tick,maxTick(store.get()),speed);}
function stopPlayback(){playing=false;tick=0;audio.stop();}

$('newProject').onclick=newProject;$('openProject').onclick=()=>$('projectFile').click();$('projectFile').onchange=openProject;$('saveProject').onclick=save;$('importMidi').onclick=()=>$('midiFile').click();$('midiFile').onchange=()=>importMidi($('midiFile').files[0]);$('importImage').onclick=()=>$('imageFile').click();$('imageFile').onchange=()=>importImage($('imageFile').files[0]);$('compilePreview').onclick=compile;$('exportShow').onclick=exportShow;$('launchDebug').onclick=launch;$('stopDebug').onclick=()=>debug.stop();$('stopDebugSide').onclick=()=>debug.stop();$('copyLogs').onclick=()=>navigator.clipboard?.writeText($('debugLogs').textContent);$('play').onclick=togglePlay;$('pause').onclick=()=>{playing=false};$('stopPlayback').onclick=stopPlayback;$('mute').onclick=()=>{audio.setMuted(!audio.muted);$('mute').textContent=audio.muted?'🔇':'🔊'};$('speed').oninput=e=>{speed=Number(e.target.value);$('speedLabel').textContent=`${speed.toFixed(2)}×`};$('timeline').oninput=e=>{tick=Number(e.target.value);playing=false};$('gridToggle').onchange=e=>{stage2d.showGrid=e.target.checked;stage2d.draw()};$('paletteSelect').onchange=e=>{stage2d.setPalette(e.target.value);renderPalette()};document.querySelectorAll('[data-tool]').forEach(b=>b.onclick=()=>{stage2d.setTool(b.dataset.tool);document.querySelectorAll('[data-tool]').forEach(x=>x.classList.toggle('active',x===b));});document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>switchView(b.dataset.view));$('fitView').onclick=()=>currentView==='stage2d'?stage2d.fit():currentView==='roll'?roll.resize():stage3d.resize();$('resetView').onclick=()=>stage2d.resetView();$('undo').onclick=()=>history.undo();$('redo').onclick=()=>history.redo();document.addEventListener('keydown',e=>{const mod=e.ctrlKey||e.metaKey;if(mod&&e.key.toLowerCase()==='z'){e.preventDefault();history.undo();}else if(mod&&e.key.toLowerCase()==='y'){e.preventDefault();history.redo();}else if(mod&&e.key.toLowerCase()==='c'&&currentView==='stage2d'){e.preventDefault();stage2d.copySelection();}else if(mod&&e.key.toLowerCase()==='v'&&currentView==='stage2d'){e.preventDefault();stage2d.pasteSelection();}else if(e.key==='Delete'&&currentView==='roll'){roll.deleteSelected();}else if(e.code==='Space'&&!['INPUT','TEXTAREA','SELECT'].includes(document.activeElement.tagName)){e.preventDefault();playing?$('pause').click():togglePlay();}});
$('snapSelect').onchange=e=>{roll.snap=Number(e.target.value)||1;roll.draw();};
$('rotateLeft').onclick=()=>rotateImage(270).catch(e=>toast(e.message));$('rotateRight').onclick=()=>rotateImage(90).catch(e=>toast(e.message));$('resetRotation').onclick=()=>{const current=Number(optionsOf(store.get()).imageRotation||0);if(current)rotateImage((360-current)%360).catch(e=>toast(e.message));};

(async()=>{await preparePalette();renderInfo();renderOptions();renderPalette();requestAnimationFrame(transportFrame);debug.refresh();})();
