export class PianoRoll {
  constructor(canvas, store, history, inspector) {
    this.canvas=canvas;this.store=store;this.history=history;this.inspector=inspector;this.zoomX=1;this.noteMin=21;this.noteMax=108;this.snap=1;this.selected=new Set();this.drag=null;this.onChange=null;
    canvas.addEventListener('dblclick',e=>this.add(e));canvas.addEventListener('pointerdown',e=>this.down(e));canvas.addEventListener('pointermove',e=>this.move(e));canvas.addEventListener('pointerup',()=>this.up());canvas.addEventListener('wheel',e=>{e.preventDefault();this.zoomX=Math.max(.2,Math.min(8,this.zoomX*(e.deltaY<0?1.1:.9)));this.draw();},{passive:false});window.addEventListener('resize',()=>this.resize());store.subscribe(()=>this.draw());this.resize();
  }
  resize(){const d=devicePixelRatio||1;this.canvas.width=Math.max(1,this.canvas.clientWidth*d);this.canvas.height=Math.max(1,this.canvas.clientHeight*d);this.canvas.getContext('2d').setTransform(d,0,0,d,0,0);this.draw();}
  maxTick(){return Math.max(120,...(this.store.get().events||[]).map(e=>Number(e.tick||0)+Number(e.durationTicks||1)));}
  metrics(){const w=this.canvas.clientWidth,h=this.canvas.clientHeight;return {w,h,row:Math.max(8,Math.min(22,h/(this.noteMax-this.noteMin+1))),left:44,unit:Math.max(2,((w-44)/Math.max(120,this.maxTick()))*this.zoomX)};}
  point(e){const r=this.canvas.getBoundingClientRect(),m=this.metrics();return {tick:Math.max(0,Math.round(((e.clientX-r.left-m.left)/m.unit)/this.snap)*this.snap),note:this.noteMax-Math.floor((e.clientY-r.top)/m.row)};}
  eventAt(e){const r=this.canvas.getBoundingClientRect(),m=this.metrics(),x=e.clientX-r.left,y=e.clientY-r.top;const list=this.store.get().events||[];for(let i=list.length-1;i>=0;i--){const n=list[i],nx=m.left+n.tick*m.unit,ny=(this.noteMax-n.note)*m.row;if(x>=nx&&x<=nx+Math.max(4,n.durationTicks*m.unit)&&y>=ny&&y<=ny+m.row)return n;}return null;}
  draw(){const ctx=this.canvas.getContext('2d'),m=this.metrics();ctx.clearRect(0,0,m.w,m.h);ctx.fillStyle='#0b111d';ctx.fillRect(0,0,m.w,m.h);for(let n=this.noteMin;n<=this.noteMax;n++){const y=(this.noteMax-n)*m.row;if(n%12===1||n%12===3||n%12===6||n%12===8||n%12===10){ctx.fillStyle='#111b2c';ctx.fillRect(0,y,m.w,m.row);}ctx.strokeStyle=n%12===0?'#486080':'#263750';ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(m.w,y);ctx.stroke();}ctx.strokeStyle='#273951';for(let t=0;t<=this.maxTick();t+=Math.max(1,this.snap*4)){const x=m.left+t*m.unit;ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,m.h);ctx.stroke();}ctx.fillStyle='#8da0be';ctx.font='10px system-ui';for(let n=this.noteMin;n<=this.noteMax;n+=12)ctx.fillText(String(n),4,(this.noteMax-n)*m.row+11);for(const e of this.store.get().events||[]){const x=m.left+e.tick*m.unit,y=(this.noteMax-e.note)*m.row;const hue=195+(Number(e.velocity||80)/127)*115;ctx.fillStyle=`hsl(${hue},75%,${this.selected.has(e.id)?68:48}%)`;ctx.fillRect(x,y,Math.max(3,e.durationTicks*m.unit),Math.max(4,m.row-2));if(this.selected.has(e.id)){ctx.strokeStyle='#fff';ctx.strokeRect(x,y,Math.max(3,e.durationTicks*m.unit),Math.max(4,m.row-2));}}if(this.playhead!=null){ctx.strokeStyle='#ffdc72';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(m.left+this.playhead*m.unit,0);ctx.lineTo(m.left+this.playhead*m.unit,m.h);ctx.stroke();}}
  add(e){const p=this.point(e);if(p.note<this.noteMin||p.note>this.noteMax)return;const id=`event-${Date.now()}-${Math.random().toString(16).slice(2)}`;const before=this.history.snapshot();const s=this.store.get();s.eventsOverride=true;s.events=[...(s.events||[]),{id,tick:p.tick,note:p.note,velocity:100,durationTicks:Math.max(1,this.snap*4),track:0,channel:0,order:s.events?.length||0}].sort((a,b)=>a.tick-b.tick||a.note-b.note);this.history.record('新增音符',before);this.selected=new Set([id]);this.inspector?.({type:'event',event:s.events.find(x=>x.id===id)});this.onChange?.();this.draw();}
  down(e){const n=this.eventAt(e);if(!n)return;const r=this.canvas.getBoundingClientRect(),m=this.metrics(),localX=e.clientX-r.left;const right=m.left+(n.tick+n.durationTicks)*m.unit;this.canvas.setPointerCapture?.(e.pointerId);this.drag={event:n,start:this.point(e),before:this.history.snapshot(),mode:localX>=right-6?'resize':'move',orig:{tick:n.tick,note:n.note,durationTicks:n.durationTicks}};this.selected=new Set([n.id]);this.inspector?.({type:'event',event:n});this.draw();}
  move(e){if(!this.drag)return;const p=this.point(e),d=this.drag.event;if(this.drag.mode==='resize'){d.durationTicks=Math.max(1,p.tick-this.drag.orig.tick);}else{d.tick=Math.max(0,this.drag.orig.tick+(p.tick-this.drag.start.tick));d.note=Math.max(this.noteMin,Math.min(this.noteMax,this.drag.orig.note+(p.note-this.drag.start.note)));}this.draw();}
  up(){if(!this.drag)return;this.history.record('移动音符',this.drag.before);this.drag=null;this.onChange?.();}
  setPlayhead(t){this.playhead=t;this.draw();}
  selectedEvent(){return this.store.get().events?.find(e=>this.selected.has(e.id));}
  updateSelected(fields){const before=this.history.snapshot();this.store.get().eventsOverride=true;for(const e of this.store.get().events||[])if(this.selected.has(e.id))Object.assign(e,fields);this.history.record('修改音符',before);this.onChange?.();this.draw();}
  deleteSelected(){if(!this.selected.size)return;const before=this.history.snapshot();this.store.get().eventsOverride=true;this.store.get().events=(this.store.get().events||[]).filter(e=>!this.selected.has(e.id));this.history.record('删除音符',before);this.selected.clear();this.onChange?.();this.draw();}
}
